//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class Okuyucular
    {
        public int OkuyucuId { get; set; }
        public string OkuyucuAd { get; set; }
        public string OkuyucuSoyad { get; set; }
        public string OkuyucuTC { get; set; }
        public string OkuyucuMail { get; set; }
        public string OkuyucuTelefon { get; set; }
        public string OkuyucuCinsiyet { get; set; }
    }
}
