//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KutuphaneOtomasyonu
{
    using System;
    using System.Collections.Generic;
    
    public partial class ÖdünçKitaplar
    {
        public int ÖdünçId { get; set; }
        public int AlanOkuyucuId { get; set; }
        public int VerenOkuyucuId { get; set; }
        public int KitapId { get; set; }
        public System.DateTime AlışTarihi { get; set; }
        public Nullable<System.DateTime> VerişTarihi { get; set; }
        public bool GeriVerildiMi { get; set; }
    
        public virtual Kaynaklar Kaynaklar { get; set; }
        public virtual Okuyucular Okuyucular { get; set; }
        public virtual Okuyucular Okuyucular1 { get; set; }
    }
}
